
server:
  port: 8080

# 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mp?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456

  # MyBatis-Plus 核心配置
  mybatis-plus:
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
      db-config:
        id-type: auto
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: org.example.entity


  # RabbitMQ 配置
  rabbitmq:
    host: 47.116.136.128
    port: 5672
    username: admin
    password: admin123
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        prefetch: 1
        acknowledge-mode: manual
  # redis 配置
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
